import 'package:flutter/material.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'Agrolith',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'home': 'Home',
      'chat': 'Chat',
      'voice': 'Voice',
      'disease': 'Disease',
      'market': 'Market',
      'schemes': 'Schemes',
      'soil': 'Soil',
      'weather': 'Weather',
      'profile': 'Profile',
      'settings': 'Settings',
      'history': 'History',
      'logout': 'Logout',
      'loading': 'Loading...',
      'error_occurred': 'An error occurred',
      'retry': 'Retry',
      'send': 'Send',
      'listening': 'Listening...',
      'processing': 'Processing...',
      'speaking': 'Speaking...',
      'tap_to_speak': 'Tap to speak',
      'select_language': 'Select Language',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'welcome': 'Welcome',
      'analyze': 'Analyze',
      'results': 'Results',
      'advice': 'Advice',
      'severity': 'Severity',
      'symptoms': 'Symptoms',
      'treatments': 'Treatments',
      'prevention': 'Prevention',
    },
    'hi': {
      'app_name': 'कृषिमित्र',
      'login': 'लॉग इन करें',
      'register': 'रजिस्टर करें',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'submit': 'जमा करें',
      'cancel': 'रद्द करें',
      'home': 'होम',
      'chat': 'चैट',
      'voice': 'आवाज़',
      'disease': 'बीमारी',
      'market': 'बाज़ार',
      'schemes': 'योजनाएं',
      'soil': 'मिट्टी',
      'weather': 'मौसम',
      'profile': 'प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'history': 'इतिहास',
      'logout': 'लॉग आउट',
      'loading': 'लोड हो रहा है...',
      'error_occurred': 'एक त्रुटि हुई',
      'retry': 'पुनः प्रयास करें',
      'send': 'भेजें',
      'listening': 'सुन रहा है...',
      'processing': 'प्रसंस्करण...',
      'speaking': 'बोल रहा है...',
      'tap_to_speak': 'बोलने के लिए टैप करें',
      'select_language': 'भाषा चुनें',
      'dark_mode': 'डार्क मोड',
      'light_mode': 'लाइट मोड',
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'शुभ दोपहर',
      'good_evening': 'शुभ संध्या',
      'welcome': 'स्वागत है',
      'analyze': 'विश्लेषण करें',
      'results': 'परिणाम',
      'advice': 'सलाह',
      'severity': 'गंभीरता',
      'symptoms': 'लक्षण',
      'treatments': 'उपचार',
      'prevention': 'निवारण',
    },
    'te': {
      'app_name': 'కృషిమిత్ర',
      'login': 'లాగిన్',
      'register': 'నమోదు చేయండి',
      'email': 'ఈమెయిల్',
      'password': 'పాస్వర్డ్',
      'submit': 'సమర్పించండి',
      'cancel': 'రద్దు చేయండి',
      'home': 'హోమ్',
      'chat': 'చాట్',
      'voice': 'వాయిస్',
      'disease': 'వ్యాధి',
      'market': 'మార్కెట్',
      'schemes': 'పథకాలు',
      'soil': 'మట్టి',
      'weather': 'వాతావరణం',
      'profile': 'ప్రొఫైల్',
      'settings': 'సెట్టింగ్లు',
      'history': 'చరిత్ర',
      'logout': 'లాగ్ అవుట్',
      'loading': 'లోడ్ అవుతోంది...',
      'error_occurred': 'లోపం ఏర్పడింది',
      'retry': 'మళ్లీ ప్రయత్నించండి',
      'send': 'పంపండి',
      'listening': 'వింటున్నాను...',
      'processing': 'ప్రాసెస్ చేస్తోంది...',
      'speaking': 'మాట్లాడుతున్నాను...',
      'tap_to_speak': 'మాట్లాడటానికి నొక్కండి',
      'select_language': 'భాషను ఎంచుకోండి',
      'dark_mode': 'డార్క్ మోడ్',
      'light_mode': 'లైట్ మోడ్',
      'good_morning': 'శుభోదయం',
      'good_afternoon': 'శుభ మధ్యాహ్నం',
      'good_evening': 'శుభ సాయంత్రం',
      'welcome': 'స్వాగతం',
      'analyze': 'విశ్లేషించండి',
      'results': 'ఫలితాలు',
      'advice': 'సలహా',
      'severity': 'తీవ్రత',
      'symptoms': 'లక్షణాలు',
      'treatments': 'చికిత్సలు',
      'prevention': 'నివారణ',
    },
    'ta': {
      'app_name': 'கிருஷிமித்ரா',
      'login': 'உள்நுழைக',
      'register': 'பதிவு செய்',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'submit': 'சமர்ப்பி',
      'cancel': 'ரத்து செய்',
      'home': 'முகப்பு',
      'chat': 'அரட்டை',
      'voice': 'குரல்',
      'disease': 'நோய்',
      'market': 'சந்தை',
      'schemes': 'திட்டங்கள்',
      'soil': 'மண்',
      'weather': 'வானிலை',
      'profile': 'சுயவிவரம்',
      'settings': 'அமைப்புகள்',
      'history': 'வரலாறு',
      'logout': 'வெளியேறு',
      'loading': 'ஏற்றுகிறது...',
      'error_occurred': 'பிழை ஏற்பட்டது',
      'retry': 'மீண்டும் முயற்சி செய்',
      'send': 'அனுப்பு',
      'listening': 'கேட்கிறது...',
      'processing': 'செயலாக்குகிறது...',
      'speaking': 'பேசுகிறது...',
      'tap_to_speak': 'பேச தட்டவும்',
      'select_language': 'மொழியைத் தேர்ந்தெடு',
      'dark_mode': 'இருண்ட பயன்முறை',
      'light_mode': 'ஒளி பயன்முறை',
      'good_morning': 'காலை வணக்கம்',
      'good_afternoon': 'மதிய வணக்கம்',
      'good_evening': 'மாலை வணக்கம்',
      'welcome': 'வரவேற்பு',
      'analyze': 'பகுப்பாய்வு',
      'results': 'முடிவுகள்',
      'advice': 'ஆலோசனை',
      'severity': 'தீவிரம்',
      'symptoms': 'அறிகுறிகள்',
      'treatments': 'சிகிச்சைகள்',
      'prevention': 'தடுப்பு',
    },
    'mr': {
      'app_name': 'कृषिमित्र',
      'login': 'लॉगिन करा',
      'register': 'नोंदणी करा',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'submit': 'सबमिट करा',
      'cancel': 'रद्द करा',
      'home': 'मुख्यपृष्ठ',
      'chat': 'चॅट',
      'voice': 'आवाज',
      'disease': 'रोग',
      'market': 'बाजार',
      'schemes': 'योजना',
      'soil': 'माती',
      'weather': 'हवामान',
      'profile': 'प्रोफाइल',
      'settings': 'सेटिंग्ज',
      'history': 'इतिहास',
      'logout': 'लॉग आउट',
      'loading': 'लोड होत आहे...',
      'error_occurred': 'त्रुटी आली',
      'retry': 'पुन्हा प्रयत्न करा',
      'send': 'पाठवा',
      'listening': 'ऐकत आहे...',
      'processing': 'प्रक्रिया करत आहे...',
      'speaking': 'बोलत आहे...',
      'tap_to_speak': 'बोलण्यासाठी टॅप करा',
      'select_language': 'भाषा निवडा',
      'dark_mode': 'डार्क मोड',
      'light_mode': 'लाईट मोड',
      'good_morning': 'शुभ सकाळ',
      'good_afternoon': 'शुभ दुपार',
      'good_evening': 'शुभ संध्याकाळ',
      'welcome': 'स्वागत आहे',
      'analyze': 'विश्लेषण करा',
      'results': 'निकाल',
      'advice': 'सल्ला',
      'severity': 'तीव्रता',
      'symptoms': 'लक्षणे',
      'treatments': 'उपचार',
      'prevention': 'प्रतिबंध',
    },
  };

  static String translate(String key, String locale) {
    return _translations[locale]?[key] ?? _translations['en']?[key] ?? key;
  }
}
